// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Models.MODELS.Configurations;
using System;
using System.Collections.Generic;
#nullable disable

namespace Models.MODELS
{
    public partial class CANCHITASGOLContext : DbContext
    {
        public CANCHITASGOLContext()
        {
        }

        public CANCHITASGOLContext(DbContextOptions<CANCHITASGOLContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Pitch> Pitch { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Turns> Turns { get; set; }
        public virtual DbSet<Users> Users { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.ApplyConfiguration(new Configurations.PitchConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.RolesConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.TurnsConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.UsersConfiguration());

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
