// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.MODELS
{
    public partial class Pitch
    {
        public Pitch()
        {
            Turns = new HashSet<Turns>();
        }
        public int IdPitch { get; set; }
        public string Owner { get; set; }
        public string PlaceName { get; set; }

        public virtual ICollection<Turns> Turns { get; set; }
    }
}