// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.MODELS
{
    public partial class Pitch
    {
        public Pitch()
        {
            BlockedPitch = new HashSet<BlockedPitch>();
        }

        public string Horario { get; set; }
        public string Canchas { get; set; }
        public string Hubicacion { get; set; }
        public int? Telefono { get; set; }
        public string Nombre { get; set; }

        public virtual Users NombreNavigation { get; set; }
        public virtual ICollection<BlockedPitch> BlockedPitch { get; set; }
    }
}