// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.MODELS
{
    public partial class Roles
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
    }
}