// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.MODELS
{
    public partial class Turns
    {
        public int Id { get; set; }
        public string NameUser { get; set; }
        public string NamePitch { get; set; }
        public DateTime? Dia { get; set; }

        public virtual Users NamePitchNavigation { get; set; }
        public virtual Users NameUserNavigation { get; set; }
    }
}