// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models.MODELS;

#nullable disable

namespace Models.Migrations
{
    [DbContext(typeof(CANCHITASGOLContext))]
    partial class CANCHITASGOLContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Models.MODELS.Pitch", b =>
                {
                    b.Property<int>("IdPitch")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPitch"));

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PlaceName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("IdPitch")
                        .HasName("PK__PITCH__6C84D4CA694F1297");

                    b.ToTable("PITCH", (string)null);
                });

            modelBuilder.Entity("Models.MODELS.Roles", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Models.MODELS.Turns", b =>
                {
                    b.Property<int>("IdTurns")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_Turns");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTurns"));

                    b.Property<int>("IdUsers")
                        .HasColumnType("int")
                        .HasColumnName("Id_USERS");

                    b.Property<int>("IdPitch")
                        .HasColumnType("int")
                        .HasColumnName("Id_PITCH");

                    b.Property<DateTime>("Dia")
                        .HasColumnType("datetime");

                    b.HasKey("IdTurns", "IdUsers", "IdPitch")
                        .HasName("PK__Turns__E07395E57AB182F4");

                    b.HasIndex("IdPitch");

                    b.HasIndex("IdUsers");

                    b.ToTable("Turns");
                });

            modelBuilder.Entity("Models.MODELS.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("email");

                    b.Property<int>("Role")
                        .HasColumnType("int")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("username");

                    b.Property<string>("Userpassword")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("userpassword");

                    b.HasKey("Id");

                    b.ToTable("USERS", (string)null);
                });

            modelBuilder.Entity("Models.MODELS.Turns", b =>
                {
                    b.HasOne("Models.MODELS.Pitch", "IdPitchNavigation")
                        .WithMany("Turns")
                        .HasForeignKey("IdPitch")
                        .IsRequired()
                        .HasConstraintName("FK__Turns__Id_PITCH__4222D4EF");

                    b.HasOne("Models.MODELS.Users", "IdUsersNavigation")
                        .WithMany("Turns")
                        .HasForeignKey("IdUsers")
                        .IsRequired()
                        .HasConstraintName("FK__Turns__Id_USERS__412EB0B6");

                    b.Navigation("IdPitchNavigation");

                    b.Navigation("IdUsersNavigation");
                });

            modelBuilder.Entity("Models.MODELS.Pitch", b =>
                {
                    b.Navigation("Turns");
                });

            modelBuilder.Entity("Models.MODELS.Users", b =>
                {
                    b.Navigation("Turns");
                });
#pragma warning restore 612, 618
        }
    }
}
