// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Models.MODELS;
using System;
using System.Collections.Generic;

namespace Models.MODELS.Configurations
{
    public partial class BlockedPitchConfiguration : IEntityTypeConfiguration<BlockedPitch>
    {
        public void Configure(EntityTypeBuilder<BlockedPitch> entity)
        {
            entity.Property(e => e.IsBlocked).HasColumnName("is_blocked");

            entity.Property(e => e.NombreCancha)
                .HasMaxLength(15)
                .IsUnicode(false)
                .HasColumnName("nombre_cancha");

            entity.HasOne(d => d.NombreCanchaNavigation)
                .WithMany(p => p.BlockedPitch)
                .HasForeignKey(d => d.NombreCancha)
                .HasConstraintName("FK_Cancha_bloqueada_Pitch");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<BlockedPitch> entity);
    }
}
