// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Models.MODELS;
using System;
using System.Collections.Generic;

namespace Models.MODELS.Configurations
{
    public partial class TurnsConfiguration : IEntityTypeConfiguration<Turns>
    {
        public void Configure(EntityTypeBuilder<Turns> entity)
        {
            entity.ToTable("turns");

            entity.Property(e => e.Id).HasColumnName("id");

            entity.Property(e => e.Dia)
                .HasColumnType("date")
                .HasColumnName("dia");

            entity.Property(e => e.NamePitch)
                .HasMaxLength(15)
                .IsUnicode(false)
                .HasColumnName("name_pitch");

            entity.Property(e => e.NameUser)
                .HasMaxLength(15)
                .IsUnicode(false)
                .HasColumnName("name_user");

            entity.HasOne(d => d.NamePitchNavigation)
                .WithMany(p => p.TurnsNamePitchNavigation)
                .HasForeignKey(d => d.NamePitch)
                .HasConstraintName("FK__turns__name_pitc__74AE54BC");

            entity.HasOne(d => d.NameUserNavigation)
                .WithMany(p => p.TurnsNameUserNavigation)
                .HasForeignKey(d => d.NameUser)
                .HasConstraintName("FK__turns__name_user__73BA3083");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Turns> entity);
    }
}
