// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Models.MODELS;
using System;
using System.Collections.Generic;

namespace Models.MODELS.Configurations
{
    public partial class TurnsConfiguration : IEntityTypeConfiguration<Turns>
    {
        public void Configure(EntityTypeBuilder<Turns> entity)
        {
            entity.HasKey(e => new { e.IdTurns, e.IdUsers, e.IdPitch })
                .HasName("PK__Turns__E07395E5FDA32256");

            entity.Property(e => e.IdTurns)
                .ValueGeneratedOnAdd()
                .HasColumnName("Id_Turns");

            entity.Property(e => e.IdUsers).HasColumnName("Id_USERS");

            entity.Property(e => e.IdPitch).HasColumnName("Id_PITCH");

            entity.Property(e => e.Dias).HasColumnType("date");

            entity.HasOne(d => d.IdPitchNavigation)
                .WithMany(p => p.TurnsIdPitchNavigation)
                .HasForeignKey(d => d.IdPitch)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Turns_USERS");

            entity.HasOne(d => d.IdUsersNavigation)
                .WithMany(p => p.TurnsIdUsersNavigation)
                .HasForeignKey(d => d.IdUsers)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Turns__Id_USERS__403A8C7D");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Turns> entity);
    }
}
